# Checks that the HelloWorld nevers breaks, like True Metal

name: Hello World CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build with Maven
      run: mvn clean package

    - name: Test with Maven
      run: mvn test

    - name: Build Docker image
      run: docker build -t my-java-app .

    - name: Run Docker container
      run: docker run --rm my-java-app

    - name: Clean up Docker
      run: |
        docker rmi my-java-app
